### PR TITLE
fix: sendMessage Button styling

### LINKED ISSUE #24: styling send message button
image
@Intellimixiopce can you pls assign me  this task

### PR DESCRIPTION
**Pull request by yasaswini999**
image
@Intellimixiopce let me know if you need any changes

### CODE REVIEW

**Comment by yasaswini999** [comment]
@Intellimixiopce if you liked my contribution pls add hacktoberfest-accepted label

**Comment by Intellimixiopce** [comment]
good work @yasaswini999 ✔

**Comment by Intellimixiopce** [comment]
you can even work on dark mode if you want to. @yasaswini999

**Comment by yasaswini999** [comment]
@Intellimixiopce yeah sure will work on it

**Pull request merged**
