### PR TITLE
Create AaryanSingh0017.md

### PR DESCRIPTION
**Pull request by AaryanSingh0017**
I have created the blog , it was a hard task and took a lot of time , I hope you like it and will accept my pull request.

### CODE REVIEW

**Review by Intellimixiopce — COMMENTED** [review]
please choose only one topic and write that in 500 words so that i can merge

**Comment by AaryanSingh0017** [comment]
Ok after that where should i put the file? and what should be the name of folder.

**Comment by Intellimixiopce** [comment]
> Ok after that where should I put the file? and what should be the name of the folder?

I have already created the blogs folder in which you have to upload your blog with **your-user-name.md** name

**Comment by GyanPrakashRaj** [comment]
@Intellimixiopce  Kindly review to merge
https://github.com/Intellimixiopce/intellimixio/pull/13

**Comment by AaryanSingh0017** [comment]
Review the changes @Intellimixiopce

**Pull request merged**
